FROM ubuntu:latest

RUN apt-get update && apt-get install -y python3 python3-pip libmariadb-dev pkg-config unrar

WORKDIR /var/www/html

COPY . .

RUN pip3 install --break-system-packages -r requirements.txt

EXPOSE 8000

CMD ["flask", "run", "--host", "0.0.0.0", "--port", "8000"]
